server:
  port: 8989
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8686/wangchen/eureka/eureka,http://eureka02:8687/wangchen/eureka/eureka,http://eureka03:8688/wangchen/eureka/eureka
spring:
  application:
    name: cloud-gateway
  cloud:
    sentinel:
      enabled: true #自动化配置是否生效
      transport:
        dashboard: localhost:8080 #Sentinel控制台地址
        heartbeat-interval-ms: 1000 #应用与Sentinel控制台的心跳间隔时间
      scg:
        fallback:
          #mode: redirect #Spring Cloud Gateway 熔断后的响应模式(选择 redirect or response)
          redirect: http://www.baidu.com #Spring Cloud Gateway 响应模式为 'redirect' 模式对应的重定向 URL
          #content-type: Spring Cloud Gateway 响应模式为 'response' 模式对应的 content-type
          #mode: Spring Cloud Gateway 熔断后的响应模式(选择 redirect or response)
          #response-body: Spring Cloud Gateway 响应模式为 'response' 模式对应的响应内容
          #response-status: Spring Cloud Gateway 响应模式为 'response' 模式对应的响应码  默认429

      #以下配置应该是日志持久化用的
      #log:
        #dir: Sentinel 日志文件所在的目录(应该是日志持久化用的)
        #switch-pid: true Sentinel 日志文件名是否需要带上pid

      #以下配置不知道是不是和文件上传下载有关
      #metric:
        #charset: metric文件字符集
        #file-single-size: Sentinel metric 单个文件的大小
        #file-total-count: Sentinel metric 总文件数量
      #冷启动因子(这个对应的应该是限流里面的warm up,监控台网关没有这个配置)
      #flow:
        #cold-factor:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: cloud-client-two
          uri: lb://localhost:8785
          predicates:
            - Path=/cloud-client-two/**
