server:
  port: 10010
spring:
  application:
    name: cloud-sentinel
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      servlet:
        block-page: https://www.baidu.com/

